        while read -r pokemonID_ pokemonUniqueID_ pokemonName_ pokemonGivenName_ inventoryStatus_ currentHP_ level_ typeOne_ typeTwo_ moveOne_ moveTwo_ moveThree_ moveFour_ moveOnePP_ moveTwoPP_ moveThreePP_ moveFourPP_ HP_ attack_ defence_ special_ speed_ burn_ freeze_ paralysis_ poison_ badlyPoisoned_ sleep_ confusion_ trapped_ chargingUp_ substituted_ flinched_; do
            pokemonID="$pokemonID_"
            declare "pokemonUniqueID${countdown}"="$pokemonUniqueID_"
            pokemonName="$pokemonName_"
            pokemonGivenName="$pokemonGivenName_"
            inventoryStatus="$inventoryStatus_"
            currentHP="$currentHP_"
            declare "level${countdown}"="$level_"
            typeOne="$typeOne_"
            typeTwo="$typeTwo_"
            declare "moveOne${countdown}"="$moveOne_"
            moveTwo="$moveTwo_"
            moveThree="$moveThree_"
            moveFour="$moveFour_"
            moveOnePP="$moveOnePP_"
            moveTwoPP="$moveTwoPP_"
            moveThreePP="$moveThreePP_"
            moveFourPP="$moveFourPP_"
            declare "HP${countdown}"="$HP_"
            attack="$attack_"
            defence="$defence_"
            special="$special_"
            speed="$speed_"
            burn="$burn_"
            freeze="$freeze_"
            paralysis="$paralysis_"
            poison="$poison_"
            badlyPoisoned="$badlyPoisoned_"
            sleepStatus="$sleep_"
            confusion="$confusion_"
            trapped="$trapped_"
            chargingUp="$chargingUp_"
            seeded="$seeded_"
            substituted="$substituted_"
            flinched="$flinched_"
        done < 


